### PR TITLE
fix: wrong mnemonic prevent new one or demo 

### LINKED ISSUE #144: Make new mnemonic after generating it directly copyable from the modal
It can make the use of the wallet for newcomers easier

### LINKED ISSUE #145: When I click to generate a new mnemonic and the input field contains invalid mnemonic, an error is displayed
The expected behavior is that the mnemonic in the input field would be overwritten even if not valid

### PR DESCRIPTION
**Pull request by git-jano**
closes #144 fix: enable selecting text in generateNewMnemonic dialog
closes #145 fix: wrong mnemonic prevent new one or demo -> err moves layout

### CODE REVIEW

File: app/frontend/components/pages/login/mnemonicAuth.js [hunk 1]
```diff
@@ -59,7 +64,7 @@ const LoadByMenmonicSection = ({
       'a',
       {
         class: 'intro-link fade-in-up',
-        onClick: openGenerateMnemonicDialog,
+        onMouseDown: (e) => isLeftClick(e, openGenerateMnemonicDialog),
```
Comment (git-jano) [inline app/frontend/components/pages/login/mnemonicAuth.js]: this is to prevent mnemonic field onBlur happen before onClick (validator will show err, which moves layout, so click might end outside the button)
