### PR TITLE
Issue 175 keyboard shortcuts

### LINKED ISSUE #175: Optimize page navigation with keyboard
Since we use custom elements, navigation with Tab may not always work properly. For example, when importing JSON keyfile, enter for password prompt does not work. It would be nice to check other elements, too.

### PR DESCRIPTION
**Pull request by git-jano**
closes #175

### CODE REVIEW

**Comment by refi93** [comment]
The tabs in the initial page (Access Cardano Wallet via) aren't reachable by tabs and enter. Also the "select key file" button in the "Key File" tab is not reachable. It would be nice if they were if we want our site to be actually navigable by keyboard.

File: app/frontend/components/pages/login/loginPage.js [hunk 1]
```diff
@@ -78,14 +63,10 @@ class LoginPage extends Component {
 
 module.exports = connect(
   (state) => ({
-    mnemonic: state.mnemonic,
```
Comment (refi93) [inline app/frontend/components/pages/login/loginPage.js]: why those properties were removed from there. It isn't clear for me at first sight

File: app/frontend/actions.js [hunk 2]
```diff
@@ -141,6 +141,7 @@ module.exports = ({setState, getState}) => {
       mnemonic: CARDANOLITE_CONFIG.CARDANOLITE_DEMO_WALLET_MNEMONIC,
       mnemonicValidationError: undefined,
       walletLoadingError: undefined,
+      focus: 'goBtn',
```
Comment (refi93) [inline app/frontend/actions.js]: the name 'focus' created the impression that the element is focused while this variable is set to 'goBtn' but actually goBtn remains focused even when focus is undefined, after calling clearFocus in components.js. Therefore I would choose a less generic name for this property, perhaps "focusTo"?

File: app/frontend/components/pages/login/mnemonicAuth.js [hunk 3]
```diff
@@ -1,95 +1,144 @@
...
-    if (e.button === 0) {
-      action()
+const isLeftClick = (e, action) => {
+  if (e.button === 0) {
+    e.preventDefault()
+    action()
+  }
+}
+
+class LoadByMenmonicSectionClass extends Component {
```
Comment (refi93) [inline app/frontend/components/pages/login/mnemonicAuth.js]: typo: Menmonic

Comment (refi93) [reply app/frontend/components/pages/login/mnemonicAuth.js]: the "class" suffix is imho redundant

File: app/frontend/components/pages/receive_ada/receiveAdaPage.js [hunk 4]
```diff
@@ -11,8 +9,8 @@ const OwnAddressesList = connect('ownAddressesWithMeta')(({ownAddressesWithMeta}
     h('h2', undefined, 'My Addresses'),
     ...ownAddressesWithMeta.map((adr) =>
       h(AddressContainer, {address: adr.address, bip32path: adr.bip32StringPath})
-    ),
-    h(AddressDetailDialog)
+    )
+    // h(AddressDetailDialog) not needed anymore, as it is invoked from footer
```
Comment (refi93) [inline app/frontend/components/pages/receive_ada/receiveAdaPage.js]: then it would be probably more suitable to move the AddressDetailDialog to some higher-level scope, like components/app.js and have this dialog between "common" components

File: app/frontend/components/pages/receive_ada/addressDetailDialog.js [hunk 5]
```diff
@@ -1,96 +1,125 @@
...
-      {class: 'overlay fade-in-up'},
-      !showVerification &&
-        h('div', {
-          class: 'overlay-close-layer',
-          onClick: closeAddressDetail,
-        }),
+class AddressDetailDialogClass extends Component {
+  componentDidUpdate() {
+    this.props.showDetail && this.copyBtn && this.copyBtn.focus()
+    // known bug: Trezor emulator steals the focus
```
Comment (refi93) [inline app/frontend/components/pages/receive_ada/addressDetailDialog.js]: is it fixable?

File: app/frontend/components/pages/receive_ada/addressDetailDialog.js [hunk 6]
```diff
@@ -1,96 +1,125 @@
...
-                    {
-                      href: `https://cardanoexplorer.com/address/${showDetail.address}`,
-                      target: '_blank',
-                      class: 'address-link margin-1rem centered-row',
+                  'div',
+                  {class: 'centered-row'},
+                  h(CopyOnClick, {
+                    value: showDetail.address,
+                    tabIndex: 1,
+                    reference: (element) => {
```
Comment (refi93) [inline app/frontend/components/pages/receive_ada/addressDetailDialog.js]: I would rename this to copyBtnRef

Comment (refi93) [reply app/frontend/components/pages/receive_ada/addressDetailDialog.js]: I would try assigning this "h(CopyOnClick...)" to a variable, let's say copyOnClick and maybe then you would be able to call focus on it, without this weird passing of reference

**Comment by git-jano** [comment]
After a discussion, we've decided to keep keyboard support only in modals and forms to avoid complications in furee sustaining of the project

File: app/frontend/actions.js [hunk 7]
```diff
@@ -201,12 +201,12 @@ module.exports = ({setState, getState}) => {
   }
 
   const openAddressDetail = (state, {address, bip32path}) => {
-    const showAddressVerification = state.usingTrezor
+    const showAddressVerification = state.usingTrezor && bip32path
```
Comment (refi93) [inline app/frontend/actions.js]: I would explain in a comment that this is done to avoid  trezor checking for donation address

File: app/frontend/actions.js [hunk 8]
```diff
@@ -201,12 +201,12 @@ module.exports = ({setState, getState}) => {
...
 
   const openAddressDetail = (state, {address, bip32path}) => {
-    const showAddressVerification = state.usingTrezor
+    const showAddressVerification = state.usingTrezor && bip32path //due to donation address
     setState({
       showAddressDetail: {address, bip32path},
       showAddressVerification,
     })
-    if (showAddressVerification) {
+    if (showAddressVerification && bip32path) {
```
Comment (refi93) [inline app/frontend/actions.js]: this && bip32Path is redundant
