### PR TITLE
fix paper wallet passphrase validation, fix paper wallet mnemonic test

### LINKED ISSUE #134: When i enter invalid mnemonic the wallet freezes
If I enter `civil void tool perfect avocado sweet immense fluid arrow aerobic boil flash civil void tool perfect avocado sweet immense fluid arrow aerobic boil flash boil flash house`, the wallet allows to "login" but it will get stuck on loading screen with error in console `Uncaught (in promise) Error: Invalid mnemonic checks`

### PR DESCRIPTION
**Pull request by git-jano**
closes #134

### CODE REVIEW

File: frontend/validators.js [hunk 1]
```diff
@@ -44,7 +46,10 @@ const feeValidator = (sendAmount, transactionFee, balance) => {
 const mnemonicValidator = (mnemonic) => {
   let validationError = null
 
-  if (!validateMnemonic(mnemonic)) {
+  if (
+    !validateMnemonic(mnemonic) ||
+    (isPaperWalletMnemonic(mnemonic) && !decodePaperWalletMnemonic(mnemonic))
```
Comment (ddeath) [inline frontend/validators.js]: maybe would be cleaner to rename `isPaperWalletMnemonic` to something like `isMnemonicInPaperWalletFormat` and create function `validatePaperWalletMnemonic` which would check `isMnemonicInPaperWalletFormat` and would try to `decodePaperWalletMnemonic` so we end up with `!validateMnemonic(mnemonic) && !validatePaperWalletMnemonic(mnemonic)`

File: frontend/validators.js [hunk 2]
```diff
@@ -1,4 +1,6 @@
 const validateMnemonic = require('../wallet/mnemonic').validateMnemonic
```
Comment (refi93) [inline frontend/validators.js]: I would merge this three lines into one statement:

const {a, b, c } = require('x')
